### ISSUE TITLE
android. kakaoDevelopers 에서 account_email  셋팅 이 없을경우 비정상 종료 발생. 

### ISSUE THREAD

**Issue by khjde1207** [JeffGuKang/react-native-kakao-login#8]
![image](https://user-images.githubusercontent.com/18232924/55848353-9335cd00-5b87-11e9-8faf-f7c913a4fca9.png)

 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.kakao.usermgmt.response.model.UserAccount.getEmail()' on a null object reference
        at com.jeffgukang.ReactNativeKakao.ReactNativeKakaoLogin.convertMapUserProfile(ReactNativeKakaoLogin.java:105)
        at com.jeffgukang.ReactNativeKakao.ReactNativeKakaoLogin.access$000(ReactNativeKakaoLogin.java:37)
        at com.jeffgukang.ReactNativeKakao.ReactNativeKakaoLogin$2.onSuccess(ReactNativeKakaoLogin.java:146)
        at com.jeffgukang.ReactNativeKakao.ReactNativeKakaoLogin$2.onSuccess(ReactNativeKakaoLogin.java:133)
        at com.kakao.network.callback.ResponseCallback.onSuccessForUiThread(ResponseCallback.java:76)
        at com.kakao.network.tasks.KakaoResultTask$1$1.run(KakaoResultTask.java:78)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

https://developers.kakao.com 설정에서 사용자 이메일 수집을 체크 안할 경우 ReactNativeKakaoLogin.java:105 라인 response.putString("email", account.getEmail()); 로직에서 에러가 발생 합니다. 

참고바랍니다. 

감사합니다.

**Comment by JeffGuKang** [comment]
@khjde1207 아 생각도 못했네요. 감사합니다. 바로 반영하겠습니다.
